In [5]:
import tensorflow as tf

In [6]:
tf.__version__

'2.1.0'

## Constants and variables
1. constants can't be modified while variables can
2. from tensorflow import constant, Variable

0 dimensional tensor

In [7]:
d0 = tf.ones((1,))

In [11]:
d1 = tf.ones([1,])

In [13]:
d1 = tf.ones((2,))

In [17]:
d2 = tf.ones((2, 2))
d2

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [18]:
d3 = tf.ones((2, 2, 2))
d3

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)>

In [19]:
print(d3.numpy())

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


### Defining constants in Tensorflow

In [28]:
from tensorflow import constant, zeros, zeros_like, ones, ones_like, fill

In [23]:
a = constant(3, shape=(2, 3))
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 3, 3],
       [3, 3, 3]], dtype=int32)>

In [26]:
b = constant([1, 2, 3, 4], shape=[2, 2])
print(b)
print(b.numpy())

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
[[1 2]
 [3 4]]


In [29]:
fill([3, 3], 7)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]], dtype=int32)>

In [32]:
zeros([2, 2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [34]:
zeros_like(b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 0]], dtype=int32)>

In [37]:
x = ones(shape=[3, 3], dtype=tf.int32, name='x')
print(x)

tf.Tensor(
[[1 1 1]
 [1 1 1]
 [1 1 1]], shape=(3, 3), dtype=int32)


### Defineing and initializing variables

In [38]:
from tensorflow import Variable

In [42]:
a0 = Variable([1, 2, 3, 4, 5, 6], dtype=tf.int32, name='variable')
a0

<tf.Variable 'variable:0' shape=(6,) dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>

In [45]:
a1 = tf.constant(2, tf.float32, name='variable')
a1

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [50]:
a3 = Variable([2, 3, 3, 3], dtype=tf.float64, name='variable')
a3

<tf.Variable 'variable:0' shape=(4,) dtype=float64, numpy=array([2., 3., 3., 3.])>

## Basic operations

In [51]:
from tensorflow import ones, matmul, multiply, add, constant

### Define 0-dimentional tensors

In [58]:
A0 = constant([1])
A0

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([1], dtype=int32)>

In [56]:
B0 = constant([2])
B0

### Define 1-dimentional tensors

In [66]:
A1 = constant([1, 2])
print(A1)
A2 = constant([3, 4])
print(A2)

tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor([3 4], shape=(2,), dtype=int32)


### Define 2-dimentional tensors

In [71]:
B1 = constant([[1, 2], [3, 4]])
print(A2)
B2 = constant([[5, 6], [7, 8]])
print(B2)

tf.Tensor([3 4], shape=(2,), dtype=int32)
tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)


In [64]:
C0 = add(A0, B0)
print(C0)

tf.Tensor([3], shape=(1,), dtype=int32)


In [68]:
C1 = add(A1, B1)
print(C1)

tf.Tensor(
[[2 4]
 [4 6]], shape=(2, 2), dtype=int32)


In [73]:
C2 = add(A2, B2)
print(C2)

tf.Tensor(
[[ 8 10]
 [10 12]], shape=(2, 2), dtype=int32)


### addition operator is overloaded

In [74]:
A1 + B1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [4, 6]], dtype=int32)>

### element-wise multiply and matrix multiply

In [75]:
from tensorflow import multiply, matmul

In [81]:
A0 = tf.ones(1)
A31 = tf.fill([3, 1], 3)
A34 = ones([3, 4])
A43 = ones([4, 3])

In [82]:
multiply(A0, A0), multiply(A31, A31)

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>,
 <tf.Tensor: shape=(3, 1), dtype=int32, numpy=
 array([[9],
        [9],
        [9]], dtype=int32)>)

In [83]:
matmul(A34, A43)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]], dtype=float32)>

### reduce_sum

In [84]:
from tensorflow import ones, reduce_sum

In [90]:
a = ones([2, 3], dtype=tf.int32)
print(a)

tf.Tensor(
[[1 1 1]
 [1 1 1]], shape=(2, 3), dtype=int32)


In [91]:
ret = reduce_sum(a)
print(ret)

tf.Tensor(6, shape=(), dtype=int32)


In [92]:
print(reduce_sum(a, axis=0))

tf.Tensor([2 2 2], shape=(3,), dtype=int32)


## Advanced operations
1. basic operators, add, multiply, matmul, reduce_sum
2. advanced operators: gradient, reshape, random

In [93]:
import tensorflow as tf

In [121]:
x = tf.Variable(-1.0)


In [122]:
with tf.GradientTape(persistent=True) as tape:
    tape.watch(x)
    y = tf.multiply(x, x)

In [123]:
g = tape.gradient(y, x)
print(g)

tf.Tensor(-2.0, shape=(), dtype=float32)


In [125]:
gray = tf.random.uniform([2, 3], maxval=255, dtype='int32')
print(gray)

tf.Tensor(
[[ 16  69 227]
 [ 13 143  74]], shape=(2, 3), dtype=int32)


In [126]:
print(tf.reshape(gray, shape=[3, 2]))

tf.Tensor(
[[ 16  69]
 [227  13]
 [143  74]], shape=(3, 2), dtype=int32)
