In [12]:
import tensorflow as tf

In [21]:
print(tf.version)
print(tf.__version__)

<module 'tensorflow_core._api.v2.version' from '/Users/luke/anaconda3/lib/python3.7/site-packages/tensorflow_core/_api/v2/version/__init__.py'>
2.1.0


In [14]:
string = tf.Variable("this is a string", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.14, tf.float64)

In [19]:
print(string)
print(number)
print(floating)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is a string'>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=324>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.14>


In [17]:
rank0_tensor = tf.Variable("test", tf.string)
rank1_tensor = tf.Variable(["Test"], tf.string)
rank2_tensor = tf.Variable([["test", "ok"], ["test", "yes"]], tf.string)

In [18]:
print(tf.rank(rank0_tensor))
print(tf.rank(rank1_tensor))
print(tf.rank(rank2_tensor))

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [22]:
rank2_tensor.shape

TensorShape([2, 2])

changing shape

In [23]:
tensor1 = tf.ones([1, 2, 3])
tensor2 = tf.reshape(tensor1, [2, 3, 1])
tensor3 = tf.reshape(tensor1, [3, -1])

In [24]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


slicing tensors

In [25]:
# createing a 2d tensor

In [26]:
matrix = [[1, 2, 3, 4, 5],
         [6, 7, 8, 9, 10],
         [11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]]

In [27]:
tensor = tf.Variable(matrix, dtype=tf.int32)

In [28]:
print(tf.rank(tensor))

tf.Tensor(2, shape=(), dtype=int32)


In [29]:
print(tensor.shape)

(4, 5)


In [31]:
three = tensor[0, 2]
print(three)

tf.Tensor(3, shape=(), dtype=int32)


In [34]:
row1 = tensor[0, :]
print(row1)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [33]:
column1 = tensor[:, 0]
print(column1)

tf.Tensor([ 1  6 11 16], shape=(4,), dtype=int32)


In [37]:
row_2_and_4 = tensor[1::2]
print(row_2_and_4)

tf.Tensor(
[[ 6  7  8  9 10]
 [16 17 18 19 20]], shape=(2, 5), dtype=int32)


In [39]:
column_1_in_row_2_and_3 = tensor[1:3, 0]
print(column_1_in_row_2_and_3)

tf.Tensor([ 6 11], shape=(2,), dtype=int32)


Types of Tensors
Before we go to far, I will mention that there are diffent types of tensors. These are the most used and we will talk more in depth about each as they are used.

* Variable
* Constant
* Placeholder
* SparseTensor

With the execption of Variable all these tensors are immuttable, meaning their value may not change during execution.

For now, it is enough to understand that we use the Variable tensor when we want to potentially change the value of our tensor.