In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.2.0


In [13]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [14]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [16]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.09069388, -0.5064045 , -0.09616801,  0.8319383 ,  0.72721654,
        -0.12029092,  0.31122363,  0.32313508,  0.0169922 , -0.37163985]],
      dtype=float32)

In [22]:
tf.nn.softmax(predictions).numpy()

array([[0.0889255 , 0.04894515, 0.07376888, 0.18661419, 0.16806008,
        0.07201065, 0.11086671, 0.11219518, 0.08260723, 0.05600635]],
      dtype=float32)

In [23]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [24]:
loss_fn(y_train[:1], predictions).numpy()

2.6309412

In [25]:
model.compile(optimizer='adam',
             loss=loss_fn,
             metrics=['accuracy'])

In [26]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 1s 611us/step - loss: 0.2897 - accuracy: 0.9168
Epoch 2/5
1875/1875 [==============================] - 1s 606us/step - loss: 0.1416 - accuracy: 0.9578
Epoch 3/5
1875/1875 [==============================] - 1s 611us/step - loss: 0.1076 - accuracy: 0.9675
Epoch 4/5
1875/1875 [==============================] - 1s 617us/step - loss: 0.0870 - accuracy: 0.9727
Epoch 5/5
1875/1875 [==============================] - 1s 615us/step - loss: 0.0740 - accuracy: 0.9768


In [27]:
probability_model = tf.keras.Sequential([model,
                                        tf.keras.layers.Softmax()
                                        ])

In [28]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.35794562e-06, 9.51109413e-09, 1.90785104e-05, 5.17156906e-04,
        1.44568317e-13, 4.97818689e-07, 1.09649843e-12, 9.99459565e-01,
        1.85736303e-06, 4.10168298e-07],
       [6.25280538e-09, 2.56141793e-05, 9.99967933e-01, 3.98845532e-06,
        2.42607362e-16, 1.79844574e-06, 9.45631911e-08, 1.47622433e-13,
        6.32611432e-07, 9.57080620e-14],
       [6.10143104e-07, 9.98591363e-01, 5.72927762e-04, 1.45557658e-06,
        1.47472965e-05, 5.21623087e-06, 4.00677018e-05, 6.01086067e-04,
        1.70009851e-04, 2.46856166e-06],
       [9.99989986e-01, 4.50711735e-09, 5.28259579e-06, 2.21690868e-07,
        4.81227280e-09, 2.27490614e-06, 1.79744632e-06, 2.70845590e-07,
        2.04657602e-09, 2.41552300e-07],
       [7.12847225e-07, 2.88893267e-11, 3.83565862e-07, 3.65002095e-09,
        9.99441922e-01, 3.96131412e-08, 1.50067805e-07, 3.57851400e-06,
        1.47634830e-06, 5.51792618e-04]], dtype=float32)>

In [29]:
p = probability_model(x_test[:5])

0.9999999