In [11]:
!pip install tensorflow_probability==0.8.0rc0 --user --upgrade

  Using cached tensorflow_probability-0.8.0rc0-py2.py3-none-any.whl (2.5 MB)
  Using cached cloudpickle-1.1.1-py2.py3-none-any.whl (17 kB)
ERROR: spyder 4.1.3 requires pyqt5<5.13; python_version >= "3", which is not installed.
ERROR: spyder 4.1.3 requires pyqtwebengine<5.13; python_version >= "3", which is not installed.


In [13]:
import tensorflow_probability as tfp
import tensorflow as tf

In [14]:
tfd = tfp.distributions

In [15]:
initial_distribution = tfd.Categorical(probs=[0.8, 0.2])

In [17]:
transition_distribution = tfd.Categorical(probs=[[0.7, 0.3],
                                                [0.2, 0.8]])

In [18]:
observation_distribution = tfd.Normal(loc=[0., 15.], scale=[5., 10.])

In [19]:
model = tfd.HiddenMarkovModel(
    initial_distribution=initial_distribution,
    transition_distribution=transition_distribution,
    observation_distribution=observation_distribution,
    num_steps=7)

In [20]:
model.mean()

<tf.Tensor: shape=(7,), dtype=float32, numpy=
array([2.9999998, 5.9999995, 7.4999995, 8.25     , 8.625001 , 8.812501 ,
       8.90625  ], dtype=float32)>

In [21]:
model.log_prob(tf.zeros(shape=[7]))

<tf.Tensor: shape=(), dtype=float32, numpy=-20.120832>