In [74]:
import tensorflow as tf
import pandas as pd
import numpy as np

In [2]:
tf.__version__

'2.1.0'

# dataset shuffle
* randomly shuffle the elements of this dataset
* shuffle(buffer_size), for perfectly shuffle, buffer_size is equal to greater than the size of the dataset
* shuffle(reshuffle_each_iteration=True)

In [16]:
dataset = tf.data.Dataset.range(3)

In [18]:
list(dataset.as_numpy_iterator())

[0, 1, 2]

In [23]:
dataset = dataset.shuffle(3, reshuffle_each_iteration=False)

In [35]:
list(dataset.as_numpy_iterator())

[2, 0, 1]

# dataset repeat

In [76]:
dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3])

In [77]:
dataset = dataset.repeat(10)

In [78]:
list(dataset.as_numpy_iterator())

[1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3]

# dataframe rank
* rank(na_option='keep'), assign nan to it 

In [62]:
df = pd.DataFrame({'Animal': ['cat', 'penguin', 'dog', 'spider', 'snake'], 'Number_legs': [4, 2, 4, 8, np.nan]})

In [63]:
df

Animal  Number_legs
0      cat          4.0
1  penguin          2.0
2      dog          4.0
3   spider          8.0
4    snake          NaN

In [64]:
df['default_rank'] = df['Number_legs'].rank()
df

Animal  Number_legs  default_rank
0      cat          4.0           2.5
1  penguin          2.0           1.0
2      dog          4.0           2.5
3   spider          8.0           4.0
4    snake          NaN           NaN

In [65]:
df['max_rank'] = df['Number_legs'].rank(method='max')
df

Animal  Number_legs  default_rank  max_rank
0      cat          4.0           2.5       3.0
1  penguin          2.0           1.0       1.0
2      dog          4.0           2.5       3.0
3   spider          8.0           4.0       4.0
4    snake          NaN           NaN       NaN

In [66]:
df['min_rank'] = df['Number_legs'].rank(method='min')
df

Animal  Number_legs  default_rank  max_rank  min_rank
0      cat          4.0           2.5       3.0       2.0
1  penguin          2.0           1.0       1.0       1.0
2      dog          4.0           2.5       3.0       2.0
3   spider          8.0           4.0       4.0       4.0
4    snake          NaN           NaN       NaN       NaN

In [67]:
df['NA_bottom'] = df['Number_legs'].rank(method='min', na_option='bottom')
df

Animal  Number_legs  default_rank  max_rank  min_rank  NA_bottom
0      cat          4.0           2.5       3.0       2.0        2.0
1  penguin          2.0           1.0       1.0       1.0        1.0
2      dog          4.0           2.5       3.0       2.0        2.0
3   spider          8.0           4.0       4.0       4.0        4.0
4    snake          NaN           NaN       NaN       NaN        5.0

In [68]:
df['pct_rank'] = df['Number_legs'].rank(pct=True)
df

Animal  Number_legs  default_rank  max_rank  min_rank  NA_bottom  pct_rank
0      cat          4.0           2.5       3.0       2.0        2.0     0.625
1  penguin          2.0           1.0       1.0       1.0        1.0     0.250
2      dog          4.0           2.5       3.0       2.0        2.0     0.625
3   spider          8.0           4.0       4.0       4.0        4.0     1.000
4    snake          NaN           NaN       NaN       NaN        5.0       NaN

# numpy argmax

In [79]:
a = np.arange(6).reshape(2, 3) + 10

In [80]:
a

array([[10, 11, 12],
       [13, 14, 15]])

In [81]:
np.argmax(a)

5

In [82]:
np.argmax(a, axis=-1)

array([2, 2])

In [83]:
np.argmax(a, axis=1)

array([2, 2])

In [84]:
np.argmax(a, axis=0)

array([1, 1, 1])